# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('cNumber', models.AutoField(primary_key=True, serialize=False, verbose_name='班组号')),
                ('cType', models.CharField(max_length=10, verbose_name='班组类型')),
            ],
            options={
                'verbose_name': '班组',
                'verbose_name_plural': '班组',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('dNumber', models.AutoField(primary_key=True, serialize=False, verbose_name='仓库号')),
                ('dType', models.CharField(max_length=10, verbose_name='仓库类型')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eNumber', models.AutoField(primary_key=True, serialize=False, verbose_name='员工号')),
                ('eName', models.CharField(max_length=10, verbose_name='员工姓名')),
                ('eAge', models.IntegerField(verbose_name='员工年龄')),
                ('position', models.CharField(max_length=20, verbose_name='岗位')),
                ('way', models.CharField(max_length=10, verbose_name='用工方式')),
                ('techGrading', models.CharField(max_length=10, verbose_name='技术评级')),
                ('dateOfAdmission', models.DateField(verbose_name='入职时间')),
                ('eSex', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('cNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.Class', verbose_name='班组号')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mNumber', models.AutoField(primary_key=True, serialize=False, verbose_name='原料号')),
                ('dName', models.CharField(max_length=20, verbose_name='原料名')),
                ('dPrice', models.FloatField(verbose_name='原料单价')),
                ('dNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.Depot', verbose_name='仓库号')),
            ],
            options={
                'verbose_name': '原料',
                'verbose_name_plural': '原料',
            },
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pDate', models.DateField(verbose_name='日期')),
                ('pWeight', models.IntegerField(default=0, verbose_name='当日产品重量')),
                ('pUsed', models.IntegerField(default=0, verbose_name='当日原料使用重量')),
                ('cNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.Class', verbose_name='班组号')),
                ('mNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.Material', verbose_name='产品号')),
            ],
            options={
                'verbose_name': '产品生产',
                'verbose_name_plural': '产品生产',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pNumber', models.AutoField(primary_key=True, serialize=False, verbose_name='产品号')),
                ('pName', models.CharField(max_length=20, verbose_name='产品名')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('pNumber', models.AutoField(primary_key=True, serialize=False, verbose_name='供应商号')),
                ('pName', models.CharField(max_length=20, verbose_name='供应商名')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sDate', models.DateField(verbose_name='日期')),
                ('sAmount', models.IntegerField(default=0, verbose_name='计件产量')),
                ('sSubsidy', models.IntegerField(default=0, verbose_name='全勤补贴')),
                ('sTotal', models.IntegerField(default=0, verbose_name='工资合计')),
                ('eNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.Employee', verbose_name='员工号')),
            ],
            options={
                'verbose_name': '应收工资',
                'verbose_name_plural': '应收工资',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('sNumber', models.AutoField(primary_key=True, serialize=False, verbose_name='车间号')),
            ],
            options={
                'verbose_name': '车间',
                'verbose_name_plural': '车间',
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uDate', models.DateField(verbose_name='日期')),
                ('uAmount', models.IntegerField(verbose_name='使用量')),
                ('cNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.Class', verbose_name='班组号')),
                ('mNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.Material', verbose_name='原料号')),
            ],
            options={
                'verbose_name': '原料使用',
                'verbose_name_plural': '原料使用',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wDate', models.DateField(verbose_name='日期')),
                ('wHours', models.IntegerField(verbose_name='正常工作时数')),
                ('wOvertime', models.IntegerField(default=0, verbose_name='加班时数')),
                ('eNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.Employee', verbose_name='考勤')),
            ],
            options={
                'verbose_name': '考勤',
                'verbose_name_plural': '考勤',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='pNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.Provider', verbose_name='供应商号'),
        ),
        migrations.AddField(
            model_name='class',
            name='sNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop.Shop', verbose_name='车间号'),
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together=set([('eNumber', 'wDate')]),
        ),
        migrations.AlterUniqueTogether(
            name='usage',
            unique_together=set([('cNumber', 'mNumber', 'uDate')]),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together=set([('eNumber', 'sDate')]),
        ),
        migrations.AlterUniqueTogether(
            name='produce',
            unique_together=set([('cNumber', 'mNumber', 'pDate')]),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set([('mNumber', 'dNumber')]),
        ),
    ]
