# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='pNumber',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Workshop.Product', verbose_name='产品号'),
        ),
    ]
